name: CI

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

jobs:
  unix:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-20.04, ubuntu-22.04, macos-11, macos-12]

    defaults:
      run:
        shell: bash -l {0}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup conda environment
        uses: mamba-org/setup-micromamba@v1
        with:
          environment-file: env.yml

      - name: Configure using CMake
        run: |
          mkdir -p build
          cd build
          cmake .. \
           -DXEUS_BUILD_TESTS=ON \
           -DCMAKE_PREFIX_PATH=$CONDA_PREFIX \
           -DCMAKE_INSTALL_PREFIX=$CONDA_PREFIX

      - name: Build
        run: |
          cd build
          make

      - name: Install
        run: |
          cd build
          make install

  win:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [ windows-2019, windows-2022 ]

    defaults:
      run:
        shell: cmd /C call {0}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup conda environment
        uses: mamba-org/setup-micromamba@v1
        with:
          environment-file: env.yml
          init-shell: cmd.exe

      - name: Make build directory
        run: mkdir build

      - name: Configure using CMake
        run: |
          cmake .. ^
           -G Ninja ^
           -DCMAKE_BUILD_TYPE=Release ^
           -DXEUS_BUILD_TESTS=ON ^
           -DDEPENDENCY_SEARCH_PREFIX="%CONDA_PREFIX%\Library" ^
           -DCMAKE_PREFIX_PATH="%CONDA_PREFIX%\Library" ^
           -DCMAKE_INSTALL_PREFIX="%CONDA_PREFIX%"
        working-directory: build

      - name: Build and install
        run: |
          ninja install
        working-directory: build  
